### ISSUE TITLE
Trouble creating vm when hyper-v host is part of a cluster

### ISSUE THREAD

**Issue by selund** [ace13/foreman_hyperv#6]
This is probably a known problem since the cluster support in fog-hyperv isn't complete.
Trying to create a vm will generate a error "Failure: undefined method `clusters' for #<ForemanHyperv::Hyperv:0x007f96da783bb0>"  Foreman version is 1.15.4

**Comment by ace13** [comment]
This particular issue was actually due to credential passing in PS Remoting, something I've implemented a hacky workaround for in fog-hyperv now.

The undefined method is due to me doing development on the actual using of said clusters, before creation would fail if your machine was a part of a cluster, regardless of if trying to use the cluster or not.

**Comment by ace13** [comment]
For reference; ace13/fog-hyperv#14

**Comment by ace13** [comment]
The undefined method should be fixed as of fe4d926f0737183e827bf0c6f9970d9bb07a2640 too, thanks for poking me about it. :+1:
